const WORD_BANK = {
  easy: [
    { id: "kucing", en: "cat", hint: "A furry pet that purrs" },
    { id: "anjing", en: "dog", hint: "Man's best friend" },
    { id: "ikan", en: "fish", hint: "Lives in water" },
    { id: "buku", en: "book", hint: "You read this" },
    { id: "air", en: "water", hint: "You drink this to stay hydrated" },
    { id: "api", en: "fire", hint: "It burns and gives warmth" },
    { id: "hari", en: "day", hint: "Opposite of night" },
    { id: "mata", en: "eye", hint: "You see with this" },
    { id: "kaki", en: "foot", hint: "You walk on these" },
    { id: "nasi", en: "rice", hint: "Staple food in Indonesia" },
    { id: "susu", en: "milk", hint: "White drink from cows" },
    { id: "roti", en: "bread", hint: "Baked from flour" },
    { id: "gula", en: "sugar", hint: "Makes things sweet" },
    { id: "topi", en: "hat", hint: "Worn on the head" },
    { id: "buah", en: "fruit", hint: "Apples and bananas are these" },
    { id: "babi", en: "pig", hint: "Pink farm animal" },
    { id: "sapi", en: "cow", hint: "Gives us milk" },
    { id: "tikus", en: "mouse", hint: "Small rodent" },
    { id: "kuda", en: "horse", hint: "You can ride this animal" },
    { id: "hujan", en: "rain", hint: "Water falling from clouds" },
  ],
  medium: [
    { id: "matahari", en: "sun", hint: "The star closest to Earth" },
    { id: "bulan", en: "moon", hint: "Shines at night" },
    { id: "gunung", en: "mountain", hint: "Very tall landform" },
    { id: "pantai", en: "beach", hint: "Where sand meets the sea" },
    { id: "pohon", en: "tree", hint: "Has branches and leaves" },
    { id: "bunga", en: "flower", hint: "Colorful part of a plant" },
    { id: "kupu-kupu", en: "butterfly", hint: "Insect with colorful wings" },
    { id: "sekolah", en: "school", hint: "Where students learn" },
    { id: "rumah", en: "house", hint: "You live in this" },
    { id: "jendela", en: "window", hint: "Glass opening in a wall" },
    { id: "meja", en: "table", hint: "Furniture to put things on" },
    { id: "kursi", en: "chair", hint: "You sit on this" },
    { id: "pintu", en: "door", hint: "You open this to enter" },
    { id: "langit", en: "sky", hint: "Look up and you'll see it" },
    { id: "bintang", en: "star", hint: "Twinkles at night" },
    { id: "sungai", en: "river", hint: "Flowing body of water" },
    { id: "jembatan", en: "bridge", hint: "Cross a river on this" },
    { id: "perpustakaan", en: "library", hint: "Building full of books" },
    { id: "pelajaran", en: "lesson", hint: "What a teacher gives" },
    { id: "pengetahuan", en: "knowledge", hint: "What you gain from learning" },
  ],
  hard: [
    { id: "kecerdasan", en: "intelligence", hint: "Ability to think and learn" },
    { id: "kebahagiaan", en: "happiness", hint: "Feeling of great joy" },
    { id: "pemerintah", en: "government", hint: "Runs a country" },
    { id: "kemerdekaan", en: "independence", hint: "Freedom from control" },
    { id: "pembangunan", en: "development", hint: "Process of growth" },
    { id: "pengalaman", en: "experience", hint: "Gained through living" },
    { id: "keberanian", en: "courage", hint: "Bravery in the face of fear" },
    { id: "persahabatan", en: "friendship", hint: "Bond between friends" },
    { id: "kesempatan", en: "opportunity", hint: "A favorable chance" },
    { id: "pertanyaan", en: "question", hint: "Needs an answer" },
    { id: "kenyamanan", en: "comfort", hint: "State of ease" },
    { id: "lingkungan", en: "environment", hint: "Surroundings of a living thing" },
    { id: "pendidikan", en: "education", hint: "Process of teaching and learning" },
    { id: "keamanan", en: "security", hint: "State of being safe" },
    { id: "kehidupan", en: "life", hint: "The opposite of death" },
    { id: "perjalanan", en: "journey", hint: "A long trip" },
    { id: "kebijaksanaan", en: "wisdom", hint: "Deep understanding gained over time" },
    { id: "keindahan", en: "beauty", hint: "Quality that pleases the senses" },
    { id: "kepercayaan", en: "trust", hint: "Belief in someone's reliability" },
    { id: "kesehatan", en: "health", hint: "State of being well" },
  ],
};
